# Generated by Django 3.1.5 on 2021-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_elevation_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22, null=True)),
            ],
        ),
    ]
