# Generated by Django 3.1.5 on 2021-02-28 15:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sro', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
